### ISSUE TITLE
Adicionar campo de ID ao serviço

### ISSUE THREAD

**Issue by Isaius** [ES2-UFPI/eFix#12]
Adicionar id para ser usado como chave unica para pesquisas especificas no futuro

**Comment by Isaius** [comment]
Tive uma ideia que talvez seja melhor.  Vamos usar o ID do serviço como o ID do prestador que faz ele. Isso ja facilita duas coisas: recuperar todos os serviços de um prestador x e recuperar um serviço especifico dele.

**Comment by Isaius** [comment]
Mas isso implica que para recuperar um servico especifico teriamos que recuperar todos os serviços dele, e depois disso procurar o serviço especifico. Pelo nome talvez? o que tu acha?

**Comment by alvaro-ian** [comment]
O ID do prestador acho que é essencial ter mesmo. Além dele pode ter o do serviço também, não vejo por que não.
