### ISSUE TITLE
[2] - Endpoint de recuperação por nome

### ISSUE THREAD

**Issue by Isaius** [ES2-UFPI/eFix#17]
Adiconar endpoint para retornar serviços que contenham as palavras recebidas nos nomes

**Comment by alvaro-ian** [comment]
Seria bom que ele não diferenciasse letras maiúsculas e minúsculas pra deixar a busca mais abrangente, é algo fácil de implementar também.

**Comment by Isaius** [comment]
Adicionei a identificação de plural também, caso a busca seja no singular e o nome do serviço no plural ou vice-versa.

**Comment by alvaro-ian** [comment]
Acho que faz mais sentido ser um "and" das palavras na busca, o serviço é incluído só se tiver todas.
