### ISSUE TITLE
[3] - Acrescentar categorias no banco de dados

### ISSUE THREAD

**Issue by alvaro-ian** [ES2-UFPI/eFix#30]
Acrescentar as seguintes categorias de serviço no banco de dados:
- Eletricista
- Encanador
- Diarista
- Jardinagem
- Outros

0 story points.

**Comment by Isaius** [comment]
![image](https://user-images.githubusercontent.com/37005228/67625779-ce90a400-f818-11e9-8379-b82aa75b642e.png)

Adicionei as categorias solicitadas, exceto Outros, que foi acordado de ser removida.

**Comment by alvaro-ian** [comment]
Revisado e aprovado.
