### ISSUE TITLE
[3] - Endpoints de horários do prestador e encapsulamento

### ISSUE THREAD

**Issue by alvaro-ian** [ES2-UFPI/eFix#40]
Fazer endpoints de horários na API e funções encapsuladas para uso no projeto.

2 story points.

**Comment by Isaius** [comment]
Depois de muito tentar cheguei a conclusão que é inviável e imprático implementar a validação de disponibilidade de horario para a alocação de um novo contrato no back-end. Além de ser extremamente problemático mexer com data e horario, o que implica em muito codigo de tratamento e conversão, o que pesa demais na API, ainda temos o problema do firebase. Para validar isso são necessárias várias consultas ao banco de dados e após tentar por muito tempo cheguei a conclusão de que é impossível. As consultas são assíncronas e demoram um tempo absurdamente alto para uma API esperar, o que ou atrasa o código, ou pior, faz com que você tente usar algo que ainda não foi recuperado. Todos os endpoints anteriores faziam no maximo uma consulta, nada cruzado com serviço, contrato e prestador.
Por fim, estou mudando isso para ser feito no front-end. Irei adicionar um novo endpoint ao app de contrato que irá retornar todos os contratos para um dia especifico para facilitar o processamento no front, que poderá ser feito buscando o serviço com o endpoint ja existente, os contratos nesse novo endpoint e verificando se é possivel ou não alocar um novo na data especificada pelo usuário.
